image: ghcr.io/espressomd/docker/ubuntu-20.04:254edd4a9c6e4d7b557be73158e400f5794e4f99

variables:
  PYPRESSO: "./espresso/build/pypresso"

stages:
  - linting
  - test
  - docs

# I split the unit tests and integration tests here as they will now run in parallel.
python-unit-tests:
  stage: test
  tags:
    - swarm
  script:
    - CI/ci_scripts/_swarm_rl_install.sh
    - cd CI/unit_tests
    - pytest .

python-integration-tests:
  stage: test
  tags:
    - swarm
  script:
    - CI/ci_scripts/_swarm_rl_install.sh
    - cd CI/integration_tests
    - pytest .

# Run the espresso tests at one time.
#espresso-tests:
#  stage: test
#  tags:
#    - swarm
#  script:
#    - CI/ci_scripts/_swarm_rl_install.sh
#    - CI/ci_scripts/_build_espresso.sh
#    - cd CI
#    - ${PYPRESSO} run_espresso_test_suite.py

black:
  stage: linting
  tags:
    - swarm
  script:
    - CI/ci_scripts/_swarm_rl_install.sh
    - black --check --verbose .

flake8:
  stage: linting
  tags:
    - swarm
  script:
    - CI/ci_scripts/_swarm_rl_install.sh
    - flake8

sphinx-docs:
  stage: docs
  tags:
    - swarm
  script:
    - CI/ci_scripts/_swarm_rl_install.sh
    - cd docs ; make html
