# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

variables:
  PYPRESSSO: './espressomd/build/pypresso'
stages:
  - build
  - linting
  - test
  - docs

build-swarmrl:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r dev-rerquirements.txt
    - pip install .

build-espresso:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - cd espresso
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .

# I split the unit tests and integration tests here as they will now run in parallel.
python-unit-tests:
  stage: test
  script:
    - cd CI/unit_tests
    - pytest .

python-integration-tests:
  stage: test
  script:
    - cd CI/integration_tests
    - pytest .

# Run the espresso tests at one time.
espresso-tests:
  stage: test
  script:
    - cd CI
    - ${PYPRESSO} run_espresso_test_suite.py

black:
  stage: linting
  script:
    - black --check --verbose .

flak8:
  stage: linting
  script:
    - flake8 .

sphinx-docs:
  stage: docs
  script:
    - cd docs ; make html
